### ISSUE TITLE
--prod not passed to npm run build on ionic run cordova --prod error

### ISSUE THREAD

**Issue by HugoHeneault** [ionic-team/ionic-plugin-deploy#138]
I have an error caused by  `ionic cordova prepare` when pushing new code to Deploy.

So it's falling back to `npm run build`... but without the --prod flag. So aot is disabled. 

Look at my logs:

```log
Running with gitlab-ci-multi-runner 9.1.0 
  on IonicJS Runner 2
Using Shell executor...
Running on ip-
Cloning repository...
Cloning into '/home/gitlab-runner/'...
Checking out #### as develop...
Skipping Git submodules setup
$ fetch-updates
Checking for build process updates...
$ build-app
Fetching build dependencies...
Running: npm install

### truncated log here

npm install succeeded
Detected local install of ionic cli...
Running: ionic build --prod
[ANNOUNCE] Hi! Welcome to CLI 3.9.

           We decided to merge core plugins back into the main ionic CLI package. The @ionic/cli-plugin-ionic-angular, @ionic/cli-plugin-ionic1, @ionic/cli-plugin-cordova, and @ionic/cli-plugin-gulp plugins have all been deprecated and won't be loaded by the CLI anymore. We listened to devs and determined they added unnecessary complexity. You can uninstall them from your project(s).
           
           No functionality was removed and all commands will continue working normally. You may wish to review the CHANGELOG: https://github.com/ionic-team/ionic-cli/blob/master/CHANGELOG.md#changelog
           
           Thanks,
           The Ionic Team
           
           
[INFO] Running app-scripts build: --prod
       
[10:53:45]  build prod started ... 
[10:53:45]  clean started ... 
[10:53:45]  clean finished in 1 ms 
[10:53:45]  copy started ... 
[10:53:45]  ngc started ... 
[10:54:02]  ngc finished in 16.51 s 
[10:54:02]  preprocess started ... 
[10:54:02]  deeplinks started ... 
[10:54:04]  deeplinks finished in 2.00 s 
[10:54:04]  optimization started ... 
[10:54:04]  copy finished in 18.87 s 
[10:54:26]  optimization finished in 21.92 s 
[10:54:26]  preprocess finished in 23.93 s 
[10:54:26]  webpack started ... 
[10:56:26]  webpack finished in 120.34 s 
[10:56:26]  sass started ... 
[10:56:26]  uglifyjs started ... 
[10:56:32]  sass finished in 6.58 s 
[10:56:32]  cleancss started ... 
[10:56:37]  cleancss finished in 4.98 s 
[10:57:54]  uglifyjs finished in 87.86 s 
[10:57:54]  postprocess started ... 
[10:57:54]  postprocess finished in 95 ms 
[10:57:54]  lint started ... 
[10:57:54]  build prod finished in 248.94 s 
> ionic cordova prepare
> cordova prepare
[10:58:10]  lint finished in 16.13 s 
✖ Running command - failed!
[ERROR] An error occurred while running cordova prepare (exit code 1):

        
        (truncated) ... n config.xml. Adding it to the project
        Installing "cordova-plugin-google-analytics" for browser
        Installing "cordova-plugin-google-analytics" for ios
        Discovered plugin "cordova-plugin-inappbrowser" in config.xml. Adding it to the project
        Installing "cordova-plugin-inappbrowser" for browser
        Installing "cordova-plugin-inappbrowser" for ios
        Discovered plugin "cordova-plugin-ionic" in config.xml. Adding it to the project
        Installing "cordova-plugin-ionic" for browser
        Installing "cordova-plugin-add-swift-support" for browser
        Installing "cordova-plugin-ionic" for ios
        Plugin dependency "cordova-plugin-add-swift-support@1.7.0" already fetched, using that version.
        Installing "cordova-plugin-add-swift-support" for ios
        Discovered plugin "cordova-plugin-network-information" in config.xml. Adding it to the project
        Installing "cordova-plugin-network-information" for browser
        Installing "cordova-plugin-network-information" for ios
        Discovered plugin "cordova-plugin-screen-orientation" in config.xml. Adding it to the project
        Installing "cordova-plugin-screen-orientation" for browser
        Installing "cordova-plugin-screen-orientation" for ios
        Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
        Installing "cordova-plugin-splashscreen" for browser
        Installing "cordova-plugin-splashscreen" for ios
        Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
        Installing "cordova-plugin-statusbar" for browser
        Installing "cordova-plugin-statusbar" for ios
        Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
        Installing "cordova-plugin-whitelist" for browser
        Installing "cordova-plugin-whitelist" for ios
        Discovered plugin "cordova-plugin-wkwebview-engine" in config.xml. Adding it to the project
        Installing "cordova-plugin-wkwebview-engine" for browser
        Installing "cordova-plugin-wkwebview-engine" for ios
        apple-ios version check failed ("/usr/src/app/platforms/ios/cordova/apple_ios_version"), continuing anyways.
        Discovered plugin "cordova-plugin-x-socialsharing" in config.xml. Adding it to the project
        Installing "cordova-plugin-x-socialsharing" for browser
        Installing "es6-promise-plugin" for browser
        Installing "cordova-plugin-x-socialsharing" for ios
        Plugin dependency "es6-promise-plugin@4.1.0" already fetched, using that version.
        Installing "es6-promise-plugin" for ios
        Discovered plugin "cordova-sqlite-storage" in config.xml. Adding it to the project
        Installing "cordova-sqlite-storage" for browser
        installing external dependencies via npm
        npm install of external dependencies ok
        Installing "cordova-sqlite-storage" for ios
        installing external dependencies via npm
        npm install of external dependencies ok
        Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
        Installing "ionic-plugin-keyboard" for browser
        Installing "ionic-plugin-keyboard" for ios
        Discovered plugin "phonegap-plugin-push" in config.xml. Adding it to the project
        Installing "phonegap-plugin-push" for browser
        Installing "phonegap-plugin-push" for ios
        Failed to install 'phonegap-plugin-push': undefined
        Failed to restore plugin "phonegap-plugin-push" from config.xml. You might need to try adding it again. Error: CocoaPods was not found. Please install version 1.0.1 or greater from https://cocoapods.org/
        { Error: ENOENT: no such file or directory, open '/usr/src/app/platforms/android/build.gradle'
             at Object.fs.openSync (fs.js:652:18)
             at Object.fs.readFileSync (fs.js:553:33)
             at module.exports (/usr/src/app/scripts/forceAndroidSupportVersion.js:12:10)
             at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:189:18)
             at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:165:16)
             at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:133:20
             at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
             at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
             at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
             at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:509:49
           errno: -2,
           code: 'ENOENT',
           syscall: 'open',
           path: '/usr/src/app/platforms/android/build.gradle' }
        Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Debug
        Update IOS build setting SWIFT_OBJC_BRIDGING_HEADER to: "$(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h" for build configuration Release
        Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Debug
        Update SWIFT version to 3.0 Debug
        Update IOS build setting SWIFT_OPTIMIZATION_LEVEL to: -Onone for build configuration Debug
        Update IOS build setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to: YES for build configuration Release
        Update SWIFT version to 3.0 Release
        
ionic build failed...falling back to npm run build
Running: npm run build
npm info it worked if it ends with ok
npm info using npm@5.3.0
npm info using node@v8.2.1
npm info lifecycle ####@1.0.0~prebuild: ####@1.0.0
npm info lifecycle ####@1.0.0~build: ####@1.0.0

> ####@1.0.0 build /usr/src/app
> ionic-app-scripts build

[11:10:20]  ionic-app-scripts 2.1.4 
[11:10:20]  build dev started ... 
[11:10:20]  clean started ... 
[11:10:20]  clean finished in 8 ms 
[11:10:20]  copy started ... 
[11:10:20]  transpile started ... 
[11:10:32]  transpile finished in 11.13 s 
[11:10:32]  preprocess started ... 
[11:10:32]  deeplinks started ... 
[11:10:32]  deeplinks finished in 605 ms 
[11:10:32]  preprocess finished in 607 ms 
[11:10:32]  webpack started ... 
[11:10:33]  copy finished in 12.21 s 
[11:10:58]  webpack finished in 26.11 s 
[11:10:58]  sass started ... 
[11:11:02]  sass finished in 3.48 s 
[11:11:02]  postprocess started ... 
[11:11:02]  postprocess finished in 67 ms 
[11:11:02]  lint started ... 
[11:11:02]  build dev finished in 41.52 s 
[11:11:11]  lint finished in 8.74 s 
npm info lifecycle ####@1.0.0~postbuild:####@1.0.0
npm info ok 
npm run build succeeded
Uploading build...
Build upload successful.
Running after script...
$ clean-up
Cleaning up files...
Successful clean up
Job succeeded
```

**Comment by dwieeb** [comment]
@HugoHeneault This Deploy plugin is for the old Ionic Cloud system. Sorry for the confusion! I updated the README.

As for your issue, can you confirm this is still a problem? I'm seeing the code and it doesn't run `ionic build` anymore. It _does_ run `npm run build`, so it'll use the `build` task in your `package.json`. I'll be adding an article to our Ionic Pro knowledgebase about this issue soon.

**Comment by HugoHeneault** [comment]
Yes it seems that it was fixed, we sent a build today and it didn't call `cordova --prepare` 🎉 

Is there any Cloud Changelog somewhere?

Thanks!

**Comment by HugoHeneault** [comment]
Could you make more clear where the new doc is on the readme? Now I can't find the new doc from the README, I'm even going to https://docs.ionic.io/services/deploy/ as there is a link just above the legacy notice...

**Comment by dwieeb** [comment]
@HugoHeneault Noted. I made an issue in our backlog. 👍
