### ISSUE TITLE
Reload fails silently on Android (but with exception)

### ISSUE THREAD

**Issue by timbru31** [ionic-team/ionic-plugin-deploy#141]
The following error occurs when the update is correctly downloaded and extracted, but the redirect seems to be broken.

```
10-23 14:28:06.951 15542-22086/? I/IONIC.DEPLOY.UNZIP_DIR: /data/user/0/com.myapp.app.debug/app_ab3265e7-3253-47eb-93d7-030456824fe0
10-23 14:28:06.957 15542-15751/? I/IONIC.DEPLOY.REDIRECT: Pre-redirect cordova injection exception: java.io.FileNotFoundException: /data/user/0/com.myapp.app.debug/app_ab3265e7-3253-47eb-93d7-030456824fe0/index.html (No such file or directory)
                                                              at java.io.FileInputStream.open(Native Method)
                                                              at java.io.FileInputStream.<init>(FileInputStream.java:146)
                                                              at java.io.FileReader.<init>(FileReader.java:72)
                                                              at io.ionic.deploy.IonicDeploy.getStringFromFile(IonicDeploy.java:85)
                                                              at io.ionic.deploy.IonicDeploy.redirect(IonicDeploy.java:776)
                                                              at io.ionic.deploy.IonicDeploy.execute(IonicDeploy.java:225)
                                                              at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
                                                              at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
                                                              at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
                                                              at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
                                                              at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
                                                              at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:7)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
10-23 14:28:10.996 15542-15542/? D/CordovaWebViewImpl: >>> loadUrl(file:/data/user/0/com.myapp.app.debug/app_ab3265e7-3253-47eb-93d7-030456824fe0/index.html)
10-23 14:28:11.030 15542-15542/? D/CordovaWebViewImpl: >>> loadUrl(file:/data/user/0/com.myapp.app.debug/app_ab3265e7-3253-47eb-93d7-030456824fe0/index.html)
10-23 14:28:11.045 15542-15542/? D/CordovaWebViewImpl: onPageDidNavigate(file:///data/user/0/com.myapp.app.debug/app_ab3265e7-3253-47eb-93d7-030456824fe0/index.html)
10-23 14:28:11.047 15542-15542/? D/CordovaWebViewImpl: onPageFinished(file:///data/user/0/com.myapp.app.debug/app_ab3265e7-3253-47eb-93d7-030456824fe0/index.html)
```
(or pastebin here: https://pastebin.com/fVbWuMF2)

Cordova v7.1.0 with Android v6.3.0.  
The target device is running Android 7.0 (Samsung Galaxy Tab A 2016 [SM-T585])

**Comment by timbru31** [comment]
The issue was on our end, a method called deploy.load() before the extraction Promise was resolved correctly.
